# This workflow creates docker images that are used for building ROOT in a Jenkins pipeline
# 
# All created images are uploaded to GitHub Container registry

name: Create images v2

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        image: ["fedora34", "fedora32", "centos7", "centos8", "ubuntu22", "ubuntu20", "ubuntu18"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.image }}/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:buildready
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=gha,scope=${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image }}
